services:
  temperature-service-api:
    container_name: temperature-service 
    build: 
      context: ./temperature-service
      dockerfile: ./docker/Dockerfile        
    hostname: temperature-service            
    ports:        
      - 8082:8082
  orchestrator-api:
    container_name: orchestrator 
    build: 
      context: ./orchestrator
      dockerfile: ./docker/Dockerfile        
    hostname: orchestrator            
    ports:        
      - 8080:8080