services:
  zipcode-api:
    container_name: zipcode 
    build: 
      context: .
      dockerfile: ./docker/zipcode/Dockerfile        
    hostname: zipcode            
    ports:        
      - 8082:8082